backend:
  name: github
  repo: AerialWombat/restaurant-website

media_folder: static/assets
public_folder: assets

collections: 
  - name: menu
    label: Menu Items
    folder: menu-items
    create: true
    fields: 
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: category, label: Category, widget: select, 
          options: ["Soup",
                    "Appetizer", 
                    "House Specialties", 
                    "Seafood", 
                    "Poultry",
                    "Beef",
                    "Pork",
                    "Vegetable",
                    "Steamed",
                    "Fried Rice/Chow Mein/Lo Mein",
                    "Egg Foo Young",
                    "American",
                    "Combo"] }
      - { name: price, label: Large Size Price}
      - { name: description,  label: Item Description, widget: markdown, required: false }